[package]
name = "lume"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.52", features = ["full"] }
regex = "1.12"
samotop = "0.13"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
futures = "0.3"
hickory-resolver = "0.26"
viadkim = "0.2"
viaspf = "0.6"
rusqlite = { version = "0.39", features = ["bundled"] }
zstd = "0.13"
xxhash-rust = { version = "0.8", features = ["xxh64"] }
serde = { version = "1.0", features = ["derive"] }
mailparse = "0.16"
thiserror = "2.0"

# --- NEW SECURITY DEPENDENCIES ---
argon2 = "0.5"
password-hash = "0.6"
rand_core = "0.10"
nix = { version = "0.31.3", features = ["user", "fs"] }
axum = "0.8"
axum-server = { version = "0.8", features = ["tls-rustls"] }
tower-http = { version = "0.6", features = ["set-header", "cors", "trace"] }
uuid = { version = "1.23", features = ["v4"] }
toml = "1.1"
reqwest = { version = "0.13", features = ["json"] }
serde_json = "1.0"
getrandom = "0.4.2"
rkyv = "0.8.16"

[dev-dependencies]
